@file:Suppress("unused")

object Versions {

    const val sdkCompile = 28
    const val sdkMin = 21
    const val sdkTarget = 28

    const val adapterdelegates = "4.2.0"
    const val autovalue = "1.0.0"
    const val ahbottomnavigation = "2.3.4"
    const val androidSvg = "1.2.1"
    const val androidx_runner = "1.1.0"
    const val anko = "0.10.8"
    const val appcompat = "1.1.0-beta01"
    const val bottomnavigation = "3.0.0"
    const val cardview = "1.0.0"
    const val cicerone = "5.0.0"
    const val constraint = "2.0.0-beta2"
    const val coreKtx = "1.0.2"
    const val coroutines = "1.1.0"
    const val exoplayer = "2.10.1"
    const val firebase_auth = "16.1.0"
    const val firebase_database = "16.0.6"
    const val firebase_play_services = "16.0.1"
    const val glide = "4.8.0"
    const val gradle = "3.4.1"
    const val gson = "2.8.5"
    const val jsoup = "1.11.3"
    const val koin = "2.0.1"
    const val ktlint = "0.31.0"
    const val ktx = "1.0.1"
    const val lifecycle = "2.0.0"
    const val lightsaber = "0.9.0-beta"
    const val material = "1.1.0-alpha07"
    const val moxyVersion = "1.7.0"
    const val multidex = "2.0.1"
    const val okhttp = "4.0.0-alpha02"
    const val okhttp3Integration = "4.3.1"
    const val okhttp3_integration = "4.3.1"
    const val play_services_maps = "16.1.0"
    const val recyclerview = "1.1.0-alpha06"
    const val retrofit = "2.4.0"
    const val retrofit2_kotlin_coroutines_adapter = "0.9.2"
    const val room = "2.1.0"
    const val rx_bindings = "3.0.0-alpha1"
    const val rxandroid = "2.1.1"
    const val rxjava = "2.2.9"
    const val sjnavigation = "0.1.1"
    const val socketIoClient = "0.6.0"
    const val stetho = "1.5.1"
    const val support = "1.1.0-alpha03"
    const val thirtyinch = "0.9.0"
    const val timber = "4.7.1"
    const val transitions = "1.1.0"
    const val vectordrawable = "1.1.0-alpha01"
    const val kotlin = "1.3.21"
    const val processPhoenix = "2.0.0"
    const val trafiAnchorBottomSheetBehaviour = "0.13-alpha"

    object Test {
        const val espresso = "3.2.0"
        const val json = "20140107"
        const val junit = "4.13-beta-3"
        const val junitJupiter = "5.3.1"
        const val kluent = "1.50"
        const val koin = "2.0.1"
        const val mockito = "1.5.0"
        const val mockitoInline = "2.28.2"
        const val robolectric = "4.3"
        const val room = "2.1.0"
        const val runner = "1.2.0"
        const val assertj = "3.10.0"
    }
}